### ISSUE TITLE
Photo on the mentors page

### ISSUE THREAD

**Issue by Plinsboorg** [ohwmakers/ohwmakers-website#17]
I noticed that my photo is not displaying correctly on the website
![изображение](https://user-images.githubusercontent.com/42300339/154328499-d2f56ce3-7d82-42cd-852e-d6197f6a69c2.png)

Can you change the photo to the square version of it? I attach it below
![IMG_20190602_172716~2 (2)](https://user-images.githubusercontent.com/42300339/154328646-0f068dec-dae9-482c-9bc0-4653fa8faaf7.jpg)
 
 there is probably a better way of attaching pictures to the issues. I would be happy to know how to do it better)

**Comment by thessaly** [comment]
Thank you Dennis! I replaced the picture, it now looks like this, let me know if that's OK:

![image](https://user-images.githubusercontent.com/33497609/155702572-54e053ce-fdd8-4b8d-becd-7c01c52b9f48.png)

**Comment by Plinsboorg** [comment]
Tanks
